# Generated by Django 4.2.6 on 2024-10-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_empleado_producto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=1),
        ),
    ]
