# Generated by Django 5.1.2 on 2024-11-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_empleado_direccion_remove_empleado_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
